# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pr2otel < Formula
  desc "pr2otel is a tool to convert Pull Request to OpenTelemetry-compatible telemetry."
  homepage "https://github.com/kazuki-iwanaga/pr2otel"
  version "0.0.7-beta3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kazuki-iwanaga/pr2otel/releases/download/v0.0.7-beta3/pr2otel_Darwin_x86_64.tar.gz"
      sha256 "04a950ea9da6151d637937d5378631c4e004a729873b22b3315a0cbee4295984"

      def install
        bin.install "pr2otel"
      end
    end
    on_arm do
      url "https://github.com/kazuki-iwanaga/pr2otel/releases/download/v0.0.7-beta3/pr2otel_Darwin_arm64.tar.gz"
      sha256 "188a7f5bfb7cbeb9bc932197b34d6a979496a6d4458b15630bd020119d39b282"

      def install
        bin.install "pr2otel"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kazuki-iwanaga/pr2otel/releases/download/v0.0.7-beta3/pr2otel_Linux_x86_64.tar.gz"
        sha256 "a3561b5d16ba9f9e3a930a6a01774ba1dfc7d955079cf3405ae224f5d145bd2d"

        def install
          bin.install "pr2otel"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kazuki-iwanaga/pr2otel/releases/download/v0.0.7-beta3/pr2otel_Linux_arm64.tar.gz"
        sha256 "9bbba58a2d40a1ddd2cb6a3ec4abf5ba37803b5c7a53af52220dc00f65769953"

        def install
          bin.install "pr2otel"
        end
      end
    end
  end
end
