# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pr2trace < Formula
  desc "A CLI tool to convert Pull Request to OpenTelemetry-compatible telemetry."
  homepage "https://github.com/kazuki-iwanaga/pr2trace"
  version "0.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kazuki-iwanaga/pr2trace/releases/download/v0.0.0/pr2trace_v0.0.0_Darwin_x86_64.tar.gz"
      sha256 "392f2666719343f2af6b1fad6e71e59e26e634f7b63f51cbd2fc4154884ac936"

      def install
        bin.install "pr2trace"
      end
    end
    on_arm do
      url "https://github.com/kazuki-iwanaga/pr2trace/releases/download/v0.0.0/pr2trace_v0.0.0_Darwin_arm64.tar.gz"
      sha256 "48f288cd8288cd38932d683516388a33c202826cf38e0a89c782451bfff7383a"

      def install
        bin.install "pr2trace"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kazuki-iwanaga/pr2trace/releases/download/v0.0.0/pr2trace_v0.0.0_Linux_x86_64.tar.gz"
        sha256 "a40347f225806a74998b9d9d795eb3eff69e49aa92d3b7c20882a8861ccdeaa1"

        def install
          bin.install "pr2trace"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kazuki-iwanaga/pr2trace/releases/download/v0.0.0/pr2trace_v0.0.0_Linux_arm64.tar.gz"
        sha256 "4a19f7e99f9a582c937932f734dea4dcfa52278cd213ee6989e1d019a14a1faf"

        def install
          bin.install "pr2trace"
        end
      end
    end
  end
end
